function loadElements()
  window.x = love.graphics.newCanvas(16, 16)
  window.min = love.graphics.newCanvas(16, 16)
  love.graphics.setCanvas(window.x)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", 0, 0, 16, 16)
  love.graphics.setColor(colors.font.dark)
  love.graphics.print("X", 2.5, 4.5)
  love.graphics.setColor(colors.win.light)
  love.graphics.setLineWidth(2)
  love.graphics.line(0, 16, 0, 0, 16, 0)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(0, 16, 16, 16, 16, 0)
  love.graphics.setCanvas()
  ---
  love.graphics.setCanvas(window.min)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", 0, 0, 16, 16)
  love.graphics.setColor(colors.font.dark)
  love.graphics.setLineWidth(3)
  love.graphics.line(3, 8, 13, 8)
  love.graphics.setColor(colors.win.light)
  love.graphics.setLineWidth(2)
  love.graphics.line(0, 16, 0, 0, 16, 0)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(0, 16, 16, 16, 16, 0)
  love.graphics.setCanvas()
end
function drawUpBox(x, y, w, h, t)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", x, y, w, h)
  love.graphics.setLineWidth(t)
  love.graphics.setColor(colors.win.light)
  love.graphics.line(x, y+h, x, y, x+w, y)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(x, y+h, x+w, y+h, x+w, y)
end
function drawDownBox(x, y, w, h, t)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", x, y, w, h)
  love.graphics.setLineWidth(t)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(x, y+h, x, y, x+w, y)
  love.graphics.setColor(colors.win.light)
  love.graphics.line(x, y+h, x+w, y+h, x+w, y)
end
function drawBlueBox(x, y, w, h, t)
  love.graphics.setColor(0, 0, 120)
  love.graphics.rectangle("fill", x, y, w, h)
  love.graphics.setLineWidth(t)
  love.graphics.setColor(0,0,180)
  love.graphics.line(x, y+h, x, y, x+w, y)
  love.graphics.setColor(0, 0, 80)
  love.graphics.line(x, y+h, x+w, y+h, x+w, y)
end
