function drawXBox(x, y)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", x, y, 16, 16)
  love.graphics.setColor(colors.font.dark)
  love.graphics.print("X", x+2.5, y+4.5)
  love.graphics.setColor(colors.win.light)
  love.graphics.setLineWidth(1)
  love.graphics.line(x, y+16, x, y, x+16, y)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(x, y+16, x+16, y+16, x+16, y)
end
function drawMinBox(x, y)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", x, y, 16, 16)
  love.graphics.setColor(colors.font.dark)
  love.graphics.setLineWidth(3)
  love.graphics.line(x+3, y+8, x+13, y+8)
  love.graphics.setColor(colors.win.light)
  love.graphics.setLineWidth(1)
  love.graphics.line(x, y+16, x, y, x+16, y)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(x, y+16, x+16, y+16, x+16, y)
end
function drawUpBox(x, y, w, h, t)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", x, y, w, h)
  love.graphics.setLineWidth(t)
  love.graphics.setColor(colors.win.light)
  love.graphics.line(x, y+h, x, y, x+w, y)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(x, y+h, x+w, y+h, x+w, y)
end
function drawDownBox(x, y, w, h, t)
  love.graphics.setColor(colors.win.normal)
  love.graphics.rectangle("fill", x, y, w, h)
  love.graphics.setLineWidth(t)
  love.graphics.setColor(colors.win.dark)
  love.graphics.line(x, y+h, x, y, x+w, y)
  love.graphics.setColor(colors.win.light)
  love.graphics.line(x, y+h, x+w, y+h, x+w, y)
end
function drawBlueBox(x, y, w, h, t)
  love.graphics.setColor(0, 0, 120)
  love.graphics.rectangle("fill", x, y, w, h)
  love.graphics.setLineWidth(t)
  love.graphics.setColor(0,0,180)
  love.graphics.line(x, y+h, x, y, x+w, y)
  love.graphics.setColor(0, 0, 80)
  love.graphics.line(x, y+h, x+w, y+h, x+w, y)
end
