function loadVar()
  sys = {}
  sys.width = love.graphics.getWidth()
  sys.height = love.graphics.getHeight()
  sys.mouse = {}
  sys.mouse.p = {}
  sys.mouse.x = love.mouse.getX
  sys.mouse.y = love.mouse.getY
  sys.mouse.p.x = 0
  sys.mouse.p.y = 0
  sys.mouse.p.p = false
  sys.mouse.drag = false
  sys.w = love.graphics.getWidth()
  sys.h = love.graphics.getHeight()
  panel = {}
  panel.thick = 30
  panel.x = 0
  panel.y = 600-panel.thick
  panel.width = sys.width
  panel.height = panel.thick
  panel.s = {}
  panel.s.x = panel.x + 5
  panel.s.y = panel.y + 5
  panel.s.width = 65
  panel.s.height = 20
  panel.s.activate = false
  panel.b = {}
  panel.b[1] = 0
  panel.b[2] = 0
  panel.b[3] = 0
  panel.b[4] = 0
  panel.b[5] = 0
  panel.b[6] = 0
  panel.b[7] = 0
  test = false
  win = {}
  win[1] = {}
  win[1].x = math.random(10, 500)
  win[1].y = math.random(10, 500)
  win[1].w = 250
  win[1].h = 400
  win[1].px = win[1].x
  win[1].py = win[1].y
  win[1].ex = true
  win[1].cvs = love.graphics.newCanvas(win[1].w, win[1].h)
  win[1].fd = false
  win[1].s = 0
  win[1].min = false
  win[1].miny = 0
  win[1].title = "Chat"
  win[1].layer = 0
  win[1].panel = 0
  win[1].oldlayer = 0
  win[1].hov = false
  win[1].hover = false
  win[1].update = true
  win[2] = {}
  win[2].x = math.random(10, 500)
  win[2].y = math.random(10, 100)
  win[2].w = 650
  win[2].h = 550
  win[2].px = win[2].x
  win[2].py = win[2].y
  win[2].ex = true
  win[2].cvs = love.graphics.newCanvas(win[2].w, win[2].h)
  win[2].fd = false
  win[2].s = 0
  win[2].min = false
  win[2].miny = 0
  win[2].title = "Internet"
  win[2].layer = 0
  win[2].panel = 0
  win[2].oldlayer = 0
  win[2].hov = false
  win[2].hover = false
  win[2].update = true
  win[3] = {}
  win[3].x = math.random(10, 500)
  win[3].y = math.random(10, 500)
  win[3].w = 450
  win[3].h = 400
  win[3].px = win[3].x
  win[3].py = win[3].y
  win[3].ex = true
  win[3].cvs = love.graphics.newCanvas(win[3].w, win[3].h)
  win[3].fd = false
  win[3].s = 0
  win[3].min = false
  win[3].miny = 0
  win[3].title = "Files"
  win[3].layer = 0
  win[3].panel = 0
  win[3].oldlayer = 0
  win[3].hov = false
  win[3].hover = false
  win[3].update = true
  win[4] = {}
  win[4].x = math.random(10, 500)
  win[4].y = math.random(10, 500)
  win[4].w = 200
  win[4].h = 150
  win[4].px = win[4].x
  win[4].py = win[4].y
  win[4].ex = true
  win[4].cvs = love.graphics.newCanvas(win[4].w, win[4].h)
  win[4].fd = false
  win[4].s = 0
  win[4].min = false
  win[4].miny = 0
  win[4].title = "Antivirus"
  win[4].layer = 0
  win[4].panel = 0
  win[4].oldlayer = 0
  win[4].hov = false
  win[4].hover = false
  win[4].update = true
  win[5] = {}
  win[5].x = math.random(10, 500)
  win[5].y = math.random(10, 500)
  win[5].w = 450
  win[5].h = 400
  win[5].px = win[5].x
  win[5].py = win[5].y
  win[5].ex = true
  win[5].cvs = love.graphics.newCanvas(win[5].w, win[5].h)
  win[5].fd = false
  win[5].s = 0
  win[5].min = false
  win[5].miny = 0
  win[5].title = "Help"
  win[5].layer = 0
  win[5].panel = 0
  win[5].oldlayer = 0
  win[5].hov = false
  win[5].hover = false
  win[5].update = true
  win[6] = {}
  win[6].x = math.random(10, 500)
  win[6].y = math.random(10, 500)
  win[6].w = 400
  win[6].h = 550
  win[6].px = win[6].x
  win[6].py = win[6].y
  win[6].ex = true
  win[6].cvs = love.graphics.newCanvas(win[6].w, win[6].h)
  win[6].fd = false
  win[6].s = 0
  win[6].min = false
  win[6].miny = 0
  win[6].title = "Settings"
  win[6].layer = 0
  win[6].panel = 0
  win[6].oldlayer = 0
  win[6].hov = false
  win[6].hover = false
  win[6].update = true
  winOpen = true
  winHover = false
  minim = love.graphics.getHeight()+10
  start = {}
  start.cvs = love.graphics.newCanvas(250, 350)
  start.o = false
  start.p = false
  start.x = 0
  start.y = 600-30-350+2
  layer = {}
  layer[1] = 0
  layer[2] = 0
  layer[3] = 0
  layer[4] = 0
  layer[5] = 0
  layer[6] = 0
  layer[7] = 0
  desktop.bg.current = 0
  fade = 0
  fadeOpacity = 0
  scene = 1
  loading = 0
end
